/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sw2.gui.Mmb;

import Sw.Services.HttpHistorialCambioServicio;
import Sw.Services.MasterPanel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import sw2.Modelo.HistorialCambioServicio;

/**
 *
 * @author Pipea
 */
public class pnlHistorialServicio extends MasterPanel {

   public pnlHistorialServicio() {
        initComponents();
        configurarTabla();
        cargarHistorial();
    }

    private void configurarTabla() {
        String[] columnas = {
            "ID", "Servicio", "Usuario", "Tipo", "Campo", "Anterior", "Nuevo", "Fecha"
        };
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        tblHistorialDeCambios.setModel(modelo);
    }

    private void cargarHistorial() {
        HttpHistorialCambioServicio cliente = new HttpHistorialCambioServicio();

        cliente.obtenerHistorial().thenAccept(historial -> {
            SwingUtilities.invokeLater(() -> {
                DefaultTableModel modelo = (DefaultTableModel) tblHistorialDeCambios.getModel();
                modelo.setRowCount(0); // Limpiar tabla

                for (HistorialCambioServicio h : historial) {
                    modelo.addRow(new Object[]{
                        h.getIdHistorial(),
                        h.getIdServicio(),
                        h.getUsuario(),
                        h.getTipoCambio(),
                        h.getCampoModificado(),
                        h.getValorAnterior(),
                        h.getValorNuevo(),
                        h.getFechaCambio()
                    });
                }
            });
        }).exceptionally(ex -> {
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this,
                    "Error al obtener historial: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            });
            return null;
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorialDeCambios = new javax.swing.JTable();

        lblTitulo.setText("Historial de Cambios");

        tblHistorialDeCambios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistorialDeCambios);

        scrollPane1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(283, Short.MAX_VALUE))
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tblHistorialDeCambios;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> T getSelection() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
