/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sw2.gui.Mmb;

import Sw.Services.HttpService;
import Sw.Services.MasterPanel;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sun.net.httpserver.HttpsConfigurator;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.concurrent.CompletableFuture;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sw2.Modelo.Servicio;

/**
 *
 * @author pipe
 */
public class pnlListaServicios extends MasterPanel {

    /**
     * Creates new form pnlListaArepas
     */
    private ArrayList<Servicio> servicio;

    public pnlListaServicios() {
        initComponents();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicio = new javax.swing.JTable();

        lblTitulo.setText("Listado de Servicios");

        jScrollPane1.setViewportView(tblServicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblServicio;
    // End of variables declaration//GEN-END:variables

  private void CargarTabla() {
      
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    HttpService httpService = new HttpService();

    System.out.println("Llamando la API: http://localhost:8080/servicio/listar");

    CompletableFuture<JsonNode> responseFuture =
        httpService.get("listar", new TypeReference<JsonNode>() {});

    responseFuture.thenAccept(json -> {
        try {
            ObjectMapper mapper = new ObjectMapper();

           
            ArrayList<Servicio> servicios = mapper.convertValue(
                json, new TypeReference<ArrayList<Servicio>>() {}
            );

            
            if (servicios == null || servicios.isEmpty()) {
                throw new RuntimeException("No se encontraron servicios en la respuesta.");
            }

            this.servicio = servicios;

           
            String[] titulos = {
                "ID Servicio", "Nombre Cliente", "ID Cliente",
                "Tipo de Servicio", "Teléfono", "Fecha Servicio", "Precio"
            };

           
            Object[][] data = servicio.stream()
                .map(a -> new Object[]{
                    a.getIdServicio(),
                    a.getNombreCliente(),
                    a.getIdCliente(),
                    a.getTipoServicio(),
                    a.getTelefono(),
                    a.getFechaServicio(),
                    a.getPrecio()
                })
                .toArray(Object[][]::new);

            DefaultTableModel model = new DefaultTableModel(data, titulos) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

           
            javax.swing.SwingUtilities.invokeLater(() -> {
                tblServicio.setModel(model);
                tblServicio.setRowHeight(20);
                setCursor(Cursor.getDefaultCursor());
            });

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this,
                    "Error procesando la respuesta: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                setCursor(Cursor.getDefaultCursor());
            });
        }

    }).exceptionally(ex -> {
        ex.printStackTrace();
        javax.swing.SwingUtilities.invokeLater(() -> {
            JOptionPane.showMessageDialog(this,
                "Error al cargar servicios. Ver consola para más detalles.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            setCursor(Cursor.getDefaultCursor());
        });
        return null;
    });
}
    @Override
public Servicio getSelection() {
    int fila = tblServicio.getSelectedRow();
    if (fila == -1 || servicio == null || fila >= servicio.size()) {
        return null;
    }
    return servicio.get(fila);
}
}

