/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sw2.gui;

import Sw.Services.HttpService;
import Sw.Services.MasterPanel;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.concurrent.CompletableFuture;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import sw2.Modelo.Servicio;
import sw2.gui.Mmb.pnlListaServicios;
import sw2.gui.Mmb.pnlCUUServicio;
import sw2.gui.Mmb.pnlHistorialServicio;

/**
 *
 * @author pipe
 */
public class frmPrincipalServicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipalServicio.class.getName());

    private MasterPanel currentPanel;
    private Object currentObject;
    private Class<?> currentType;

    public frmPrincipalServicio() {
        initComponents();
        pnlContenido.setLayout(new BorderLayout());
        setResizable(false);
        setExtendedState(MAXIMIZED_BOTH);
    }

    public void setCurrentPanel(JPanel panel) {
        if (panel instanceof MasterPanel) {
            this.currentPanel = (MasterPanel) panel;
        } else {
            System.out.println("El panel no es instancia de MasterPanel: " + panel.getClass().getName());
            this.currentPanel = null;
        }
    }

    public JPanel getCurrentPanel() {
        return this.currentPanel;
    }

    public void setCurrentType(Class<?> type) {
        this.currentType = type;
    }

    public void actualizarListaServicios() {
        this.currentPanel = new pnlListaServicios();
        this.currentType = Servicio.class;
        CargarPanel(currentPanel);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecera = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        opcServicios = new javax.swing.JMenu();
        opcHistorialDeCambios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCabecera.setBackground(new java.awt.Color(0, 0, 204));

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addGap(25, 25, 25))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        opcServicios.setText("Servicios");
        opcServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcServiciosMouseClicked(evt);
            }
        });
        menuPrincipal.add(opcServicios);

        opcHistorialDeCambios.setText("Historial de cambios");
        opcHistorialDeCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcHistorialDeCambiosMouseClicked(evt);
            }
        });
        menuPrincipal.add(opcHistorialDeCambios);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void opcServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcServiciosMouseClicked
        this.currentPanel = new pnlListaServicios();
        this.currentType = Servicio.class;
        CargarPanel(currentPanel);

    }//GEN-LAST:event_opcServiciosMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (!this.isTherePanel()) {
            return;
        }

        this.currentObject = this.currentType.cast(this.currentPanel.getSelection());
        if (this.currentObject == null) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el elemento que desea eliminar");
            return;
        }

        routeModel("Eliminar", false);


    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        if (!this.isTherePanel()) {
            return;
        }

        this.currentObject = this.currentType.cast(this.currentPanel.getSelection());
        if (this.currentObject == null) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el elemento que desea editar");
            return;
        }

        routeModel("Editar", true);
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked

        this.currentObject = null;
        if (this.isTherePanel()) {
            routeModel("Nuevo", true);
        }


    }//GEN-LAST:event_btnNuevoMouseClicked

    private void opcHistorialDeCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcHistorialDeCambiosMouseClicked
     this.currentPanel = new pnlHistorialServicio();
        this.currentType = Servicio.class;
        CargarPanel(currentPanel);
    }//GEN-LAST:event_opcHistorialDeCambiosMouseClicked
    public void CargarPanel(JPanel p) {
        this.currentObject = null;
        pnlContenido.removeAll();

        if (!(pnlContenido.getLayout() instanceof BorderLayout)) {
            pnlContenido.setLayout(new BorderLayout());
        }

        pnlContenido.add(p, BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }

    private boolean isTherePanel() {
        if (this.currentPanel == null) {
            JOptionPane.showMessageDialog(rootPane, "No se visualiza ningún panel");
            return false;
        }
        return true;
    }

    private void routeModel(String titulo, boolean isCUCall) {
        MasterPanel p = null;
        long id = -1;

        if (this.currentType == Servicio.class) {
            p = new pnlCUUServicio((Servicio) this.currentObject);
            if (currentObject != null) {
                id = ((Servicio) currentObject).getIdServicio();
            }
        }

        if (!isCUCall && currentObject != null) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que deseas eliminar el servicio?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            Servicio servicio = (Servicio) currentObject;

            HttpService http = new HttpService();
            CompletableFuture<Void> responseFuture = http.delete(String.valueOf(servicio.getIdServicio()));

            responseFuture.thenAccept(res -> {
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "Elemento eliminado correctamente");
                    setCursor(Cursor.getDefaultCursor());
                    this.currentPanel = new pnlListaServicios();
                    this.currentType = Servicio.class;
                    CargarPanel(currentPanel);
                });
            }).exceptionally(ex -> {
                ex.printStackTrace();
                String mensaje = ex.getMessage().contains("404")
                        ? "El servicio ya no existe o no se encontró en el servidor"
                        : "Ha ocurrido un error eliminando el elemento:\n" + ex.getMessage();

                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                    setCursor(Cursor.getDefaultCursor());
                });
                return null;
            });
        }

        if (isCUCall && p != null) {
            CargaModal(p, titulo);
        }
    }

public void CargaModal(MasterPanel p, String titulo) {
    JDialog dialog = new JDialog(this, titulo, true);
    dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    p.setModalPadre(dialog);
    dialog.add(p);

    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (p instanceof pnlCUUServicio cuu && cuu.isActualizarLista()) {
                actualizarListaServicios();
                JOptionPane.showMessageDialog(frmPrincipalServicio.this, "Los cambios han sido guardados correctamente");
            }
        }
    });

    dialog.pack();
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu opcHistorialDeCambios;
    private javax.swing.JMenu opcServicios;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
